### ISSUE TITLE
Błąd przy budowaniu

### ISSUE THREAD

**Issue by barpec12** [cytadela8/wwi2018-ctf#1]
Przy budowaniu otrzymuję błąd. Dodam, że komendę wpisałem wraz z --recurse-submodules.
```
Building pwn
Step 1/9 : FROM wwi2018_nsjail
ERROR: Service 'pwn' failed to build: pull access denied for wwi2018_nsjail, repository does not exist or may require 'docker login'
```

**Comment by cytadela8** [comment]
Widzę, że była zmiana nazwy w pewnym momencie. Nadal miałem obraz o nazwie `wwi2018_nsjail`, więc u mnie działało. Poprawione jest. Zrób `git pull` i zbuduj pownonie.

**Comment by cytadela8** [comment]
Chyba coś nadal nie działa. Nazwy kontenerów działają dziwnie.

**Comment by cytadela8** [comment]
Chyba teraz jest dobrze.
