### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by mimi89999** [cytadela8/wwi2018-ctf#2]
Czy mógłbyś wrzucić do repo prezentację z podsumowania CTFu?

**Comment by cytadela8** [comment]
Hmm, coś nie mogę znaleźć tej prezentacji :/

**Comment by cytadela8** [comment]
A nie jednak znalazłem. Plik nie miał rozszerzenia...

**Comment by cytadela8** [comment]
@mimi89999  https://github.com/cytadela8/wwi2018-ctf/blob/master/prezentacja_podsumowanie.ods
